### ISSUE TITLE
Any ideas on how to expose camera entities directly to the add-on?

### ISSUE THREAD

**Issue by niemyjski** [mories76/ha-addon-frigate#2]
Any ideas on how to expose camera entities directly to the add-on?

**Comment by mories76** [comment]
I have no intent on facilitating this addon any longer now that frigate has its own addon.

I suggest look at the Roadmap of Frigate for any upcoming features
[https://github.com/blakeblackshear/frigate/projects/1](https://github.com/blakeblackshear/frigate/projects/1)
