### ISSUE TITLE
shm-size

### ISSUE THREAD

**Issue by floris-b** [mories76/ha-addon-frigate#4]
The shm size is set to the default 64MB but according to:
https://github.com/blakeblackshear/frigate#getting-started it should be set higher

Maybe this can be set with: 
https://developers.home-assistant.io/docs/add-ons/configuration#add-on-extended-build

**Comment by mories76** [comment]
I suggest switching to the official frigate addon. [https://github.com/blakeblackshear/frigate-hass-addons](https://github.com/blakeblackshear/frigate-hass-addons)
Starting with the 0.7.0 release frigate has moved away from the plasmastore which needed a higher shm-size which makes it easier to implement Frigate without changes to the HA supervisor
